DROP TABLE IF EXISTS people_roles CASCADE;
DROP TABLE IF EXISTS roles_permissions CASCADE;

DROP TABLE IF EXISTS fields CASCADE;
DROP TABLE IF EXISTS people CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

DROP SEQUENCE IF EXISTS gid_seq CASCADE;
